# -*- coding: utf-8 -*-
"""LIME

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6VVM-CVAbroPYam9qYw4V5QxgsJVeLR
"""

!pip install lime

import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd

import lime
import lime.lime_tabular
from lime import submodular_pick

from xgboost import XGBClassifier

from sklearn.metrics import accuracy_score
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split 
bc = load_breast_cancer()  

df = pd.DataFrame(bc.data, columns=bc.feature_names) 
df['Target'] = bc.target
df.head(5)
df.info()

df.shape

X = bc.data
Y = bc.target
feature = bc.feature_names

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.30, random_state=42)

model = XGBClassifier(n_estimators = 300, random_state = 123)
model.fit(X_train, Y_train)

Y_pred = model.predict(X_test)

accuracy = accuracy_score(Y_test, Y_pred) 
print("Accuracy: %.2f%%" % (accuracy * 100.0))

predict_fn = lambda x: model.predict_proba(x)

explainer = lime.lime_tabular.LimeTabularExplainer(df[feature].astype(int).values,
                                                   mode='classification',
                                                   class_names=['Negative', 'Positive'],
                                                   training_labels=df['Target'],
                                                   feature_names=feature)

i = 5
exp = explainer.explain_instance(df.loc[i,feature].astype(int).values, predict_fn, num_features=5)
exp.show_in_notebook(show_table=True)

figure = exp.as_pyplot_figure(label = exp.available_labels()[0])

