# -*- coding: utf-8 -*-
"""NOT_gate

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6VVM-CVAbroPYam9qYw4V5QxgsJVeLR
"""

import numpy as np
import pandas as pd
x1 = [0,1]
x2 = [[0,0],[0,1],[1,0],[1,1]]
gates = {}
gates['X'] = x2
def activation(y_hat):
    if(y_hat>=0):
        return 1
    else:
        return 0
def perceptron(x,w,b):
    y = []
    for x_hat in x:
        xw = np.dot(x_hat,w) + b
        y.append(activation(xw))
    return y
def NOT(x):
    w = [-1]
    b = 0
    # print(x)
    return perceptron(x,w,b)
not_ = NOT(x1)
print('NOT', not_)
all_w = [[0,0],[0,1],[1,0],[1,1]]
all_b = [-2, -1, 0, 1, 2]

for w in all_w:
    for b in all_b:
        temp = perceptron(x2,w,b)
        if temp == [0,1,1,1]:
            print(w, b, temp)
        
        if(NOT(temp) == [1, 0, 0, 0]):
            print(w, b, temp)

not_gate = {'X': x1, 'NOT': not_}
data = pd.DataFrame(not_gate)
print(data)

