# -*- coding: utf-8 -*-
"""OR_gate

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6VVM-CVAbroPYam9qYw4V5QxgsJVeLR
"""

import numpy as np
import pandas as pd
x1 = [0,1]
x2 = [[0,0],[0,1],[1,0],[1,1]]
gates = {}
gates['X'] = x2
def activation(y_hat):
    if(y_hat>=0):
        return 1
    else:
        return 0
def perceptron(x,w,b):
    y = []
    for x_hat in x:
        xw = np.dot(x_hat,w) + b
        y.append(activation(xw))
    return y
def OR(x):
    w = [1,1]
    b = -1
    return perceptron(x,w,b)
or_ = OR(x2)
gates['OR'] = or_
print('OR', or_)

data = pd.DataFrame(gates)
print(data)

